
package panel;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.awt.Component;
import Control.KamarControl;
import Control.CustomerControl;
import Control.PetugasControl;
import model.Kamar;
import model.Customer;
import model.Petugas;
import exception.*;
import model.Booking;

public class CustomerPanel extends javax.swing.JPanel {

    private CustomerControl cc = new CustomerControl();
    private Customer c = null;
    
    private KamarControl kamarControl;
    private CustomerControl customerControl;
    private PetugasControl petugasControl;
    
    String action = null, selectedId = "";
    private Component rootPane;
    
    List<Kamar> kamarList;
    List<Customer> customerList;
    List<Petugas> petugasList;
    
    // set count
    public void setCount(){
        kamarList = kamarControl.showListKamar();
        customerList = customerControl.showListCustomer();
        petugasList = petugasControl.showListPetugas();
        
        if(kamarList.size() < 10){
            jLabel2.setText("0" + kamarList.size());
        }else {
            jLabel2.setText("" + kamarList.size());
        }
        
        if(customerList.size() < 10){
            jLabel3.setText("0" + customerList.size());
        }else {
            jLabel3.setText("" + customerList.size());
        }
        
        if(petugasList.size() < 10){
            jLabel6.setText("0" + petugasList.size());
        }else {
            jLabel6.setText("" + petugasList.size());
        }

    }
    
    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    // EXCEPTION
    public void inputKosongException() throws InputKosongException{
        if(inputIdCustomer.getText().isEmpty() || namaTextField.getText().isEmpty() 
            || emailTextField.getText().isEmpty() || nomorTeleponTextField.getText().isEmpty()
            ||jenisKelaminGroup.getSelection() == null){
               throw new InputKosongException();
        }        
    }
    
    private void InvalidNoTelpException() throws InvalidNoTelpException{
        if(!nomorTeleponTextField.getText().matches("^\\+?[0-9]+$"))
            throw new InvalidNoTelpException();
    }
    
    //RADIO BUTTON
    public void setRadioButtonValue(){
        lakiBtn.setActionCommand("Laki-laki");
        perempuanBtn.setActionCommand("Perempuan");
    }
    
    //TABLE SHOW
    public void showTableBySearch(String target){
        TableCustomer.setModel(cc.showTable(target));
    }
    
    //Method-method

    private void setCustomerEditDeleteButton(boolean value) {
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        
        //RESET RADIOBUTTON
        jenisKelaminGroup.clearSelection();
        
        //RESET TEXT
        inputIdCustomer.setText("");
        namaTextField.setText("");
        emailTextField.setText("");
        nomorTeleponTextField.setText("");
    }
        
    public void setComponent(boolean value){
        inputIdCustomer.setEnabled(value);
        namaTextField.setEnabled(value);
        emailTextField.setEnabled(value);
        nomorTeleponTextField.setEnabled(value);
        
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }

    public void setRadioComponent(boolean value){
        lakiBtn.setEnabled(value);
        perempuanBtn.setEnabled(value);
    }

    private void doSearchCustomer() {
        if (inputSearch.getText().isEmpty())
            return;

        Customer c = cc.searchCustomerById(inputSearch.getText());

        if (c != null) {
            setCustomerEditDeleteButton(true);
            inputIdCustomer.setText(c.getId_customer());
            namaTextField.setText(c.getNama());
            emailTextField.setText(c.getEmail());
            nomorTeleponTextField.setText(c.getNo_telp());

        } else {
            JOptionPane.showMessageDialog(this,"Kamar tidak ditemukan!");
        }
    }
    
    public CustomerPanel() {
        initComponents();
        setOpaque(false);

        setRadioButtonValue();
        showTableBySearch("");
        
        customerControl = new CustomerControl();
        kamarControl = new KamarControl();
        petugasControl = new PetugasControl();
        
        //RESET
        setCount();
        clearText();
        setComponent(false);
        setRadioComponent(false);
        setCustomerEditDeleteButton(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelaminGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        judulKamarPanel = new javax.swing.JPanel();
        judulHotelLabel = new javax.swing.JLabel();
        judulCustomerLabel = new javax.swing.JLabel();
        searchCustomerPanel = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        inputSearch = new javax.swing.JTextField();
        tabelCustomerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCustomer = new javax.swing.JTable();
        jpanelRound2 = new costum.JpanelRound();
        namaLabel12 = new javax.swing.JLabel();
        countPanel = new costum.JpanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        formKamarPanel = new costum.JpanelRound();
        idPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        inputIdCustomer = new javax.swing.JTextField();
        namaPanel = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        emailPanel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        nomorTeleponPanel = new javax.swing.JPanel();
        nomorTeleponLabel = new javax.swing.JLabel();
        nomorTeleponTextField = new javax.swing.JTextField();
        kelaminPanel = new javax.swing.JPanel();
        kelaminLabel = new javax.swing.JLabel();
        lakiBtn = new javax.swing.JRadioButton();
        perempuanBtn = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        thumbnailPanel = new costum.JpanelRound();
        roomPict = new javax.swing.JLabel();
        buttonCustomerPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        mainPanel.setBackground(new java.awt.Color(244, 233, 225));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judulKamarPanel.setBackground(new java.awt.Color(244, 233, 225));

        judulHotelLabel.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        judulHotelLabel.setText("Thousand Sunny Management System");

        judulCustomerLabel.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        judulCustomerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulCustomerLabel.setText("Customer Managment");

        javax.swing.GroupLayout judulKamarPanelLayout = new javax.swing.GroupLayout(judulKamarPanel);
        judulKamarPanel.setLayout(judulKamarPanelLayout);
        judulKamarPanelLayout.setHorizontalGroup(
            judulKamarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judulKamarPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(judulKamarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judulHotelLabel)
                    .addComponent(judulCustomerLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        judulKamarPanelLayout.setVerticalGroup(
            judulKamarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(judulKamarPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(judulHotelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judulCustomerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(judulKamarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 460, 90));

        searchCustomerPanel.setBackground(new java.awt.Color(244, 233, 225));
        searchCustomerPanel.setPreferredSize(new java.awt.Dimension(141, 47));

        searchBtn.setBackground(new java.awt.Color(0, 61, 121));
        searchBtn.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon-search.png"))); // NOI18N
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        inputSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout searchCustomerPanelLayout = new javax.swing.GroupLayout(searchCustomerPanel);
        searchCustomerPanel.setLayout(searchCustomerPanelLayout);
        searchCustomerPanelLayout.setHorizontalGroup(
            searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        searchCustomerPanelLayout.setVerticalGroup(
            searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerPanelLayout.createSequentialGroup()
                .addGroup(searchCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputSearch)
                    .addComponent(searchBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        mainPanel.add(searchCustomerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 510, -1));

        tabelCustomerPanel.setBackground(new java.awt.Color(244, 233, 225));
        tabelCustomerPanel.setPreferredSize(new java.awt.Dimension(141, 47));

        TableCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableCustomer);

        jpanelRound2.setBackground(new java.awt.Color(83, 37, 103));
        jpanelRound2.setRoundBottomLeft(25);
        jpanelRound2.setRoundBottomRight(25);
        jpanelRound2.setRoundTopLeft(25);
        jpanelRound2.setRoundTopRight(25);

        namaLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        namaLabel12.setForeground(new java.awt.Color(255, 255, 255));
        namaLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLabel12.setText("Sunsets proof that endings can be beautiful.");

        javax.swing.GroupLayout jpanelRound2Layout = new javax.swing.GroupLayout(jpanelRound2);
        jpanelRound2.setLayout(jpanelRound2Layout);
        jpanelRound2Layout.setHorizontalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelRound2Layout.setVerticalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(namaLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabelCustomerPanelLayout = new javax.swing.GroupLayout(tabelCustomerPanel);
        tabelCustomerPanel.setLayout(tabelCustomerPanelLayout);
        tabelCustomerPanelLayout.setHorizontalGroup(
            tabelCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelCustomerPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(tabelCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabelCustomerPanelLayout.setVerticalGroup(
            tabelCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabelCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        mainPanel.add(tabelCustomerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 490, 690));

        countPanel.setBackground(new java.awt.Color(83, 37, 103));
        countPanel.setRoundBottomLeft(25);
        countPanel.setRoundBottomRight(25);
        countPanel.setRoundTopLeft(25);
        countPanel.setRoundTopRight(25);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rooms count");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 65)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("00");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 65)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("00");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Customer count");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Waiter count");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 65)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("00");

        javax.swing.GroupLayout countPanelLayout = new javax.swing.GroupLayout(countPanel);
        countPanel.setLayout(countPanelLayout);
        countPanelLayout.setHorizontalGroup(
            countPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(countPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(countPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(countPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(countPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        countPanelLayout.setVerticalGroup(
            countPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(countPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(countPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(countPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, countPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(countPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        mainPanel.add(countPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 430, 150));

        formKamarPanel.setBackground(new java.awt.Color(83, 37, 103));
        formKamarPanel.setRoundBottomLeft(25);
        formKamarPanel.setRoundBottomRight(25);
        formKamarPanel.setRoundTopLeft(25);
        formKamarPanel.setRoundTopRight(25);

        idPanel.setBackground(new java.awt.Color(83, 37, 103));

        idLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));
        idLabel.setText("ID Customer");

        inputIdCustomer.setBackground(new java.awt.Color(83, 37, 103));
        inputIdCustomer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inputIdCustomer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputIdCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idPanelLayout = new javax.swing.GroupLayout(idPanel);
        idPanel.setLayout(idPanelLayout);
        idPanelLayout.setHorizontalGroup(
            idPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputIdCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366))
        );
        idPanelLayout.setVerticalGroup(
            idPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputIdCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaPanel.setBackground(new java.awt.Color(83, 37, 103));

        namaLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(255, 255, 255));
        namaLabel.setText("Nama Lengkap");

        namaTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namaTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        namaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaPanelLayout = new javax.swing.GroupLayout(namaPanel);
        namaPanel.setLayout(namaPanelLayout);
        namaPanelLayout.setHorizontalGroup(
            namaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLabel)
                .addGap(26, 26, 26)
                .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        namaPanelLayout.setVerticalGroup(
            namaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaLabel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        emailPanel.setBackground(new java.awt.Color(83, 37, 103));

        emailLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Alamat Email");

        emailTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emailTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout emailPanelLayout = new javax.swing.GroupLayout(emailPanel);
        emailPanel.setLayout(emailPanelLayout);
        emailPanelLayout.setHorizontalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        emailPanelLayout.setVerticalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nomorTeleponPanel.setBackground(new java.awt.Color(83, 37, 103));

        nomorTeleponLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nomorTeleponLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomorTeleponLabel.setText("Nomor Telepon");

        nomorTeleponTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nomorTeleponTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nomorTeleponTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorTeleponTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nomorTeleponPanelLayout = new javax.swing.GroupLayout(nomorTeleponPanel);
        nomorTeleponPanel.setLayout(nomorTeleponPanelLayout);
        nomorTeleponPanelLayout.setHorizontalGroup(
            nomorTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomorTeleponPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomorTeleponLabel)
                .addGap(19, 19, 19)
                .addComponent(nomorTeleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        nomorTeleponPanelLayout.setVerticalGroup(
            nomorTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nomorTeleponPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomorTeleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomorTeleponLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kelaminPanel.setBackground(new java.awt.Color(83, 37, 103));

        kelaminLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        kelaminLabel.setForeground(new java.awt.Color(255, 255, 255));
        kelaminLabel.setText("Jenis Kelamin");

        jenisKelaminGroup.add(lakiBtn);
        lakiBtn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lakiBtn.setForeground(new java.awt.Color(255, 255, 255));
        lakiBtn.setText("Laki-laki");

        jenisKelaminGroup.add(perempuanBtn);
        perempuanBtn.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        perempuanBtn.setForeground(new java.awt.Color(255, 255, 255));
        perempuanBtn.setText("Perempuan");

        javax.swing.GroupLayout kelaminPanelLayout = new javax.swing.GroupLayout(kelaminPanel);
        kelaminPanel.setLayout(kelaminPanelLayout);
        kelaminPanelLayout.setHorizontalGroup(
            kelaminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kelaminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kelaminLabel)
                .addGap(44, 44, 44)
                .addComponent(lakiBtn)
                .addGap(18, 18, 18)
                .addComponent(perempuanBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kelaminPanelLayout.setVerticalGroup(
            kelaminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelaminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kelaminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelaminLabel)
                    .addComponent(lakiBtn)
                    .addComponent(perempuanBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveBtn.setBackground(new java.awt.Color(13, 110, 253));
        saveBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.setBorder(null);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(220, 53, 69));
        cancelBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.setBorder(null);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formKamarPanelLayout = new javax.swing.GroupLayout(formKamarPanel);
        formKamarPanel.setLayout(formKamarPanelLayout);
        formKamarPanelLayout.setHorizontalGroup(
            formKamarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formKamarPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(formKamarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelaminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formKamarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nomorTeleponPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(emailPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formKamarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        formKamarPanelLayout.setVerticalGroup(
            formKamarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formKamarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(namaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kelaminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomorTeleponPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(formKamarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(formKamarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 640, 370));

        thumbnailPanel.setRoundBottomLeft(50);
        thumbnailPanel.setRoundBottomRight(50);
        thumbnailPanel.setRoundTopLeft(50);
        thumbnailPanel.setRoundTopRight(50);

        roomPict.setFont(new java.awt.Font("Arial", 1, 3)); // NOI18N
        roomPict.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomPict.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customerPict.png"))); // NOI18N
        roomPict.setToolTipText("");

        javax.swing.GroupLayout thumbnailPanelLayout = new javax.swing.GroupLayout(thumbnailPanel);
        thumbnailPanel.setLayout(thumbnailPanelLayout);
        thumbnailPanelLayout.setHorizontalGroup(
            thumbnailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(thumbnailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(roomPict, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thumbnailPanelLayout.setVerticalGroup(
            thumbnailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(thumbnailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(roomPict, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(thumbnailPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 640, 220));

        buttonCustomerPanel.setBackground(new java.awt.Color(244, 233, 225));
        buttonCustomerPanel.setPreferredSize(new java.awt.Dimension(141, 47));

        addBtn.setBackground(new java.awt.Color(0, 61, 121));
        addBtn.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(255, 183, 0));
        editBtn.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Edit");
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(220, 53, 69));
        deleteBtn.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonCustomerPanelLayout = new javax.swing.GroupLayout(buttonCustomerPanel);
        buttonCustomerPanel.setLayout(buttonCustomerPanelLayout);
        buttonCustomerPanelLayout.setHorizontalGroup(
            buttonCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonCustomerPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(buttonCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttonCustomerPanelLayout.setVerticalGroup(
            buttonCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonCustomerPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        mainPanel.add(buttonCustomerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 17, 210, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        showTableBySearch(inputSearch.getText());

        clearText();
        setComponent(false);
        setCustomerEditDeleteButton(false);
        setRadioComponent(false);
        jenisKelaminGroup.clearSelection();
        addBtn.setEnabled(true);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void inputSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputSearchMouseClicked

    }//GEN-LAST:event_inputSearchMouseClicked

    private void TableCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCustomerMouseClicked
        int indexCustomer = -1;
        action = "edit";

        addBtn.setEnabled(false);
        deleteBtn.setEnabled(true);
        saveBtn.setEnabled(true);
        setCustomerEditDeleteButton(true);

        setComponent(false);
        setRadioComponent(false);
        jenisKelaminGroup.clearSelection();

        int clickedRow = TableCustomer.getSelectedRow();
        TableModel tableModel = TableCustomer.getModel();

        String selectedIdCustomer = tableModel.getValueAt(clickedRow, 0).toString();
        selectedId = selectedIdCustomer;
        inputIdCustomer.setText(tableModel.getValueAt(clickedRow, 0).toString());
        namaTextField.setText(tableModel.getValueAt(clickedRow, 1).toString());

        emailTextField.setText(tableModel.getValueAt(clickedRow, 2).toString());
        nomorTeleponTextField.setText(tableModel.getValueAt(clickedRow, 3).toString());

        String jenisKelamin = tableModel.getValueAt(clickedRow, 4).toString();

        switch(jenisKelamin){
            case "Laki-laki" :
            lakiBtn.setSelected(true);
            break;
            case "Perempuan" :
            perempuanBtn.setSelected(true);
            break;
        }

        cancelBtn.setEnabled(true);
        inputIdCustomer.setEnabled(false);
    }//GEN-LAST:event_TableCustomerMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        action = "delete";

        int dialog = JOptionPane.showConfirmDialog(this, "yakin ingin melakukan " + action + "?");
        if(dialog == JOptionPane.CLOSED_OPTION || dialog == JOptionPane.NO_OPTION || dialog == JOptionPane.CANCEL_OPTION){
            return;
        } else if (dialog == JOptionPane.OK_OPTION){
           cc.deleteDataCustomer(selectedId);
        }

        setCount();
        clearText();
        setComponent(false);
        inputIdCustomer.setEnabled(false);
        namaTextField.setEnabled(false);
        emailTextField.setEnabled(false);
        nomorTeleponTextField.setEnabled(false);
        setCustomerEditDeleteButton(false);
        setRadioComponent(false);
        addBtn.setEnabled(true);
        showTableBySearch("");
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked

    }//GEN-LAST:event_editBtnMouseClicked

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        action = "edit";
        setComponent(true);
        inputIdCustomer.setEnabled(false);
        namaTextField.setEnabled(true);
        emailTextField.setEnabled(true);
        nomorTeleponTextField.setEnabled(true);
        setCustomerEditDeleteButton(true);
        setRadioComponent(true);
    }//GEN-LAST:event_editBtnActionPerformed

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked

    }//GEN-LAST:event_addBtnMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        action = "add";
        setComponent(true);
        setRadioComponent(true);
        
        inputIdCustomer.setEnabled(false);
        inputIdCustomer.setText(cc.generateId());
    }//GEN-LAST:event_addBtnActionPerformed

    private void inputIdCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdCustomerActionPerformed

    private void namaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void nomorTeleponTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorTeleponTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorTeleponTextFieldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try{

            // EXCEPTION
            inputKosongException();
            InvalidNoTelpException();
            
            String jenisKelamin = "";

            jenisKelamin = jenisKelaminGroup.getSelection().getActionCommand();
            
            int dialog = JOptionPane.showConfirmDialog(this, "yakin ingin melakukan " + action + "?");
            if(dialog == JOptionPane.CLOSED_OPTION || dialog == JOptionPane.NO_OPTION || dialog == JOptionPane.CANCEL_OPTION){
                return;
            } else if (dialog == JOptionPane.OK_OPTION){
                if(action.equals("add")){
                    Customer data = new Customer(
                        inputIdCustomer.getText(),
                        namaTextField.getText(),
                        emailTextField.getText(),
                        nomorTeleponTextField.getText(),
                        jenisKelamin);
                    cc.InsertDataCustomer(data);
                } else {
                    Customer data = new Customer(
                        inputIdCustomer.getText(),
                        namaTextField.getText(),
                        emailTextField.getText(),
                        nomorTeleponTextField.getText(),
                        jenisKelamin);
                    cc.updateCustomer(data,selectedId);
                    selectedId = "-1";
                }
            }
            
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch(InvalidNoTelpException e){
            JOptionPane.showMessageDialog(rootPane, e.message());
        }

        setCount();
        clearText();
        setComponent(false);
        setCustomerEditDeleteButton(false);;
        setRadioComponent(false);
        jenisKelaminGroup.clearSelection();
        addBtn.setEnabled(true);
        showTableBySearch("");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        clearText();
        setComponent(false);
        setCustomerEditDeleteButton(false);
        setRadioComponent(false);

        addBtn.setEnabled(true);
    }//GEN-LAST:event_cancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableCustomer;
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel buttonCustomerPanel;
    private javax.swing.JButton cancelBtn;
    private costum.JpanelRound countPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JTextField emailTextField;
    private costum.JpanelRound formKamarPanel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel idPanel;
    private javax.swing.JTextField inputIdCustomer;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jenisKelaminGroup;
    private costum.JpanelRound jpanelRound2;
    private javax.swing.JLabel judulCustomerLabel;
    private javax.swing.JLabel judulHotelLabel;
    private javax.swing.JPanel judulKamarPanel;
    private javax.swing.JLabel kelaminLabel;
    private javax.swing.JPanel kelaminPanel;
    private javax.swing.JRadioButton lakiBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel namaLabel12;
    private javax.swing.JPanel namaPanel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel nomorTeleponLabel;
    private javax.swing.JPanel nomorTeleponPanel;
    private javax.swing.JTextField nomorTeleponTextField;
    private javax.swing.JRadioButton perempuanBtn;
    private javax.swing.JLabel roomPict;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JPanel searchCustomerPanel;
    private javax.swing.JPanel tabelCustomerPanel;
    private costum.JpanelRound thumbnailPanel;
    // End of variables declaration//GEN-END:variables
}
